### ISSUE TITLE
Node.js / JavaScript msgpack cannot parse membership body

### ISSUE THREAD

**Issue by greglearns** [hashicorp/serf#136]
Serf version: 0.4.1
Node.js version: 0.10.25

Seems like Serf RPC cannot be used from Node.js / JavaScript because the msgpack packages for Node.js cannot parse the msgpack messages sent by Serf?

Probably related to: https://github.com/hashicorp/serf/issues/100

1) Msgpack headers CAN be parsed. However, msgpack.unpack returns only the header value, ignoring anything after the header.
```javascript
msgpack.unpack('��Error��Seq\03��Num\01')
{ Error: '', Seq: 3 }  // should also return { Num: 1 }, but does not.
```
// NOTE: the data for unpack, shown above, was generated from reading msgpack data via TCP using serf's RPC. I am just cutting and pasting the log message here so that you can see what it looks like.

2) Msgpack bodies CAN be parsed for 'join' commands, if you first parse the message (which will return the header), and then you skip past the bytes for the header and then try to unpack the remainder of the message:
```javascript
function hackyUnpack(data)
    var header = msgpack.unpack(data)
    var len = msgpack.pack(header).length
    if (len < data.length) {
      body = msgpack.unpack(data.slice(len)
}

hackyUnpack('��Error��Seq\03��Num\01')
{ Error: '', Seq: 3 }
{ Num: 1 }
```

3) Msgpack bodies CANNOT be parsed for 'membership' commands, or any command that has a complex body:

```javascript
hackyUnpack('��Error��Seq\02��Event�member-join�Members���Addr�\04\01�DelegateCur\03�DelegateMax\03�DelegateMin\01�Name�agent-1�Port�� �ProtocolCur\02�ProtocolMax\02�ProtocolMin\01�Status�alive�Tags��role�testing123')
Error: Error de-serializing object
```
I have tried all of the msgpack implementations on NPMjs.org, and all have this problem.

**Comment by Downchuck** [comment]
Is this still an issue? The node.js projects seem to have stalled:
* https://github.com/calmera/node-serfer
* https://github.com/hden/node-serf
* https://github.com/normanjoyner/serf-rpc

**Comment by slackpad** [comment]
Haven't heard anything on this one in a while - proposing we close it out unless people feel that a Serf change is needed.
