### ISSUE TITLE
Invalid agent address data in the `Addr` field of `members` command.

### ISSUE THREAD

**Issue by spikeekips** [hashicorp/serf#158]
I am trying to apply the `serf` in my python based application and I decided to use `rpc` with `msgpack-python` library (https://pypi.python.org/pypi/msgpack-python) for communicating with the agent.

Everything seems to be ok. I wrote the simple python script to get the msgpack data thru rpc and got the valid parsed data. But I found some weired `Addr` data in the parsed data after the received data was load/unpack from the response of `members` command. The parsed data looked like this,

``` python
  {'Addr': '\xc0\xa8\x00\x16',
   'DelegateCur': 4,
   'DelegateMax': 4,
   'DelegateMin': 1,
   'Name': 'machine16',
   'Port': 7916,
   'ProtocolCur': 2,
   'ProtocolMax': 2,
   'ProtocolMin': 1,
   'Status': 'alive',
   'Tags': {}},
  {'Addr': '\xc0\xa8\x00\x16',
   'DelegateCur': 4,
   'DelegateMax': 4,
   'DelegateMin': 1,
   'Name': 'machine12',
   'Port': 7912,
   'ProtocolCur': 2,
   'ProtocolMax': 2,
   'ProtocolMin': 1,
   'Status': 'alive',
   'Tags': {}},
```

I ran the 16 agents in the one remote server, `192.168.0.22` for test, so I guess the first line, `{'Addr': '\xc0\xa8\x00\x16',` should be `{'Addr': [192, 168, 0, 22],` according to the `serf` documentation page, http://www.serfdom.io/docs/agent/rpc.html .

I don't know whether the `msgpack-python` library could not parsed correctly, or it was the matter of the bad packed data from `serf` agent.

Thanks.

ps. This is my python script for test.

``` python
import sys
import pprint
import socket
import msgpack


host = '192.168.0.22'
port = 7316

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM, )
s.settimeout(10, )

s.connect((host, port, ), )

msg_handshake = msgpack.packb(dict(
        Command='handshake',
        Seq=0,
    ), ) + msgpack.packb(dict(Version=1, ), )

msg_members = msgpack.packb(dict(
        Command='members',
        Seq=1,
    ), )


s.sendall(msg_handshake, )
s.sendall(msg_members + '\n', )

data = ''
while True :
    try :
        _data = s.recv(8192, )
        if not _data :
            break

        data += _data
    except socket.timeout, e :
        print '[e] %s' % e
        sys.exit(1, )
        break

unpacker = msgpack.Unpacker(use_list=True, )
unpacker.feed(data)

for i in unpacker :
    pprint.pprint(i, )

s.close()

```

**Comment by charleswhchan** [comment]
@ryanuber, @armon has the message packing for 'Addr' changed since [previous discussions](https://github.com/hashicorp/serf/issues/158#issuecomment-36654584)? Currently looking a longer string when using serfclient-py --> `'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xc4\xa8?\x91'`

Trying to understand the format so I could try and fix: https://github.com/KushalP/serfclient-py/issues/20

Thanks!

**Comment by charleswhchan** [comment]
(Answered my own question.)

Looks like 'Addr' is now msgpack of IPv6:
```
import socket
print socket.inet_ntop(socket.AF_INET6, addr)
::ffff:192.168.1.108
```
