### ISSUE TITLE
Multiple responses pr. node

### ISSUE THREAD

**Issue by eirslett** [hashicorp/serf#253]
I'm building a service discovery layer on top of Serf, implemented as a Scala client library that interacts with Serf via the RPC protocol.
We run a number of servers, each with multiple business applications (modules/services in a SOA architecture), and these applications have redundant instances across the physical servers, so in case one goes down, the service is fault tolerant.
Then plan is to run 1 Serf agent pr. physical server and let these agents form a cluster. Then, for the discovery layer, each business application instance maintains a client connection to the Serf agent running on the same machine as the application itself.
When you start a new application, it would send a "who-is-online?" query to the cluster, and each application instance should respond with "i-am-online" and its host/port. The problem is that I can only seem to send one response pr Serf agent pr query, so if two applications interact with the same Serf node, the response fails.

Would it be possible to configure Serf so that it accepts one query response pr. client/RPC connection, instead of pr. Serf node? Is that an enhancement that would be accepted if we sent a PR?

**Comment by slackpad** [comment]
Closing this out because Consul looks like a viable solution for the given use case. Please reopen if you'd like to keep pursuing this.
