### ISSUE TITLE
Website causes Firefox to freeze on Linux

### ISSUE THREAD

**Issue by derekchiang** [hashicorp/serf#259]
My Firefox freezes and subsequently crashes every time I open serfdom.io.  It's the newest version of Firefox (35.0) on Ubuntu 14.10.

Chrome does not have this issue.

I suspect it's the fancy javascript effect (the one where you can drag the nodes in the caption image) that's causing the problem.

**Comment by slackpad** [comment]
Haven't gotten any recent complaints about this and seems good with the latest Firefox, closing this out. Please reopen if you see any issues.
