### ISSUE TITLE
Output from `serf members -format json` is not always json

### ISSUE THREAD

**Issue by schlueter** [hashicorp/serf#262]
We ran into an issue where we're consuming the output of `serf members -format json` and if there is no serf agent running, the output of that command is not json, and so the application fails because it can't parse the output as json. 

Things could probably be said about how that serf consuming application is written, but it seems like if you request output in json, you should always get output in json.

**Comment by ryanuber** [comment]
Hey @schlueter,
The intended way to avoid this is to check the exit code first. Only in cases where the exit code is 0 (we actually got a list of members) should the output buffer be parsed as JSON. If the agent isn't running, you should get exit code 1.

**Comment by schlueter** [comment]
Cool, I figured your answer would be something like that. Honestly, I don't think I would have written that wrapper the way it was.
