### ISSUE TITLE
flapping nodes on big cluster

### ISSUE THREAD

**Issue by lclementi** [hashicorp/serf#269]
Hi,
we are testing serf on a big cluster (2K nodes), all nodes are in the same network segment.
The internal network used for serf is a 10Gb network and all node are top of the line Haswell with 100GB of RAM.

I consistently see nodes in the cluster flapping (about 1 every hour) even when there is no load on the cluster:
```
Feb 24 01:44:15 test-dev serf[14966]: serf: EventMemberFailed: comet-02-07.local 10.1.255.176
Feb 24 01:44:16 test-dev serf[14966]: agent: Received event: member-failed
Feb 24 01:44:16 test-dev serf[14966]: serf: EventMemberJoin: comet-02-07.local 10.1.255.176
Feb 24 01:44:17 test-dev serf[14966]: agent: Received event: member-join
```

In the log I also see a ton of:
```
Feb 24 01:21:18 xxxx serf[14966]: memberlist: Potential blocking operation. Last command took 23.075001ms
Feb 24 01:23:18 xxxx serf[14966]: memberlist: Potential blocking operation. Last command took 10.009121ms
```
Which is probably connected with https://github.com/hashicorp/serf/issues/102 with the difference that here we are talking about high end hardware.

I also see a lot of:
```
Feb 24 00:53:00 test-dev serf[14966]: memberlist: Initiating push/pull sync with: 10.1.249.107:7946
Feb 24 00:56:30 test-dev serf[14966]: memberlist: Initiating push/pull sync with: 10.1.250.206:7946
Feb 24 00:59:05 test-dev serf[14966]: memberlist: Responding to push/pull sync with: 10.1.253.92:58808
Feb 24 01:00:00 test-dev serf[14966]: memberlist: Initiating push/pull sync with: 10.1.255.68:7946
Feb 24 01:03:31 test-dev serf[14966]: memberlist: Initiating push/pull sync with: 10.1.254.72:7946
```

I'm on a centos 6.5.

```
# serf info
agent:
	name = comet-dev.sdsc.edu
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 26
	max_procs = 1
	os = linux
	version = go1.4.1
serf:
	encrypted = true
	event_queue = 0
	event_time = 3
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 973
	members = 1894
	query_queue = 0
	query_time = 1
tags:
```

Should I try to use -profile wan (even if I'm running on a LAN)?

Luca

**Comment by armon** [comment]
Hey @lclementi! What version of Serf are you running? There are some major stability fixes for large clusters in 0.6.4 which may help. Additionally, setting `GOMAXPROCS` to 2 may help any potential scheduler blocking issues.

**Comment by lclementi** [comment]
Hey @armon,
thank for your help. I'm already on 0.6.4.

# serf version
Serf v0.6.4
Agent Protocol: 4 (Understands back to: 2)

I changed the maxprocs, let's see what happen.

Luca

**Comment by armon** [comment]
@lclementi If you see it happening again, it would be useful to have the debug level log output as well. Also the telemetry from Serf (via a SIGUSR1 signal) would be great too.

**Comment by lclementi** [comment]
So the flapping nodes always had this type of error in the logs:

2015/02/25 08:09:57 [ERR] memberlist: Failed to send ping: write udp:
invalid argument
2015/02/25 08:09:58 [ERR] memberlist: Failed to send ping: write udp:
invalid argument
2015/02/25 08:09:59 [ERR] memberlist: Failed to send ping: write udp:
invalid argument

In our case the problem seems to be related with our 10Gbe transceivers that are flapping.

Although this problem can also happen when your ARP table is not big enough for your cluster size (see https://github.com/hashicorp/serf/issues/263).

Luca
