### ISSUE TITLE
Sending SERF events from external processes 

### ISSUE THREAD

**Issue by carlskii** [hashicorp/serf#270]
Hi, I'm new to SERF and have requirement to trigger the sending of a custom event from an external process. Is there a SERF client library that can be used to do this? If so are there any examples available?

Thanks.

**Comment by carlskii** [comment]
I think I found it.

https://github.com/hashicorp/serf/blob/master/client/rpc_client.go

**Comment by ryanuber** [comment]
@carlskii you can use the [RPC Protocol](https://serfdom.io/docs/agent/rpc.html) to control Serf from a remote process. Keep in mind that you will need to encode messages using Msgpack. The documentation shows JSON because it is easier to demonstrate the request/response structures.
