### ISSUE TITLE
targeting custom events

### ISSUE THREAD

**Issue by carlskii** [hashicorp/serf#271]
HI,

I've been reading the SERF docs and one thing I'm not clear on is how to target custom events to specific nodes. For example I have a two node (n1 & n2) cluster, but want a custom event to fire a specific provisioning script on n2 only. Is this controlled purely by what event handlers are configured on the nodes or am I missing something obvious here? 

Thanks.

**Comment by ryanuber** [comment]
Hey @carlskii,

Serf doesn't provide a built-in way of filtering events, but this can be easily achieved by implementing the filtering inside of the handler script. Have a look at the [event handler documentation](https://serfdom.io/docs/agent/event-handlers.html). A good way to do filtering is to send a payload with the event, and then check against the node name or tags in the handler script, which are exported as environment variables.
