### ISSUE TITLE
Network Scan for other clients

### ISSUE THREAD

**Issue by canausa** [hashicorp/serf#274]
Some networks do not allow multicast and as such client should ( with a flag options ) scan the network for other clients or some other ability to detect client on the same network without multicast

**Comment by ryanuber** [comment]
@canausa thanks for the suggestion. Scanning the network is a very expensive and intrusive way of detecting close-by peers, so I think we would need to take an alternate approach. Let's leave this open as an enhancement for now. Thanks!

**Comment by slackpad** [comment]
There hasn't been much more interest in this one so I'm going to close it out. The SRV record support in development is a good alternative - https://github.com/hashicorp/serf/issues/305.
