### ISSUE TITLE
Query needs more documentation

### ISSUE THREAD

**Issue by canausa** [hashicorp/serf#276]
It should be better documented that an event handler must be defined in the format of -even-handler "query:load=uptime" I only found this form the ops example folder on github.

**Comment by ryanuber** [comment]
@canausa This is documented on the event handlers page [here](https://serfdom.io/docs/agent/event-handlers.html), under the "Specifying Event Handlers" section. Please have a look there. If there is something specific, please let us know what you think would clear it up, we would be happy to add it!

**Comment by canausa** [comment]
https://serfdom.io/intro/getting-started/queries.html nor do any links on the left side tell you about going in to the "docs" section at the top to find out how to setup a custom query.

**Comment by ryanuber** [comment]
@canausa thanks for pointing that out. I've fixed this and added a link to the mentioned documentation in 4bd6183.
