### ISSUE TITLE
-join should filter its before trying to connect

### ISSUE THREAD

**Issue by canausa** [hashicorp/serf#278]
If you trying something like the command below you will see messages about it trying to connect to 3 servers when in reality it is only 1 server.

serf agent -join=127.0.0.1 -join=127.0.0.1 -join=127.0.0.1

**Comment by ryanuber** [comment]
Joining multiple nodes is actually a harmless, idempotent process. Serf will only attempt to join until it is successful one time, so in this case only the first attempt would actually execute.
