### ISSUE TITLE
Serf should save cluster state by default

### ISSUE THREAD

**Issue by canausa** [hashicorp/serf#279]
When you start a cluster it should save some state by default so that you do not need to specify -join again or run the serf join $IP

**Comment by ryanuber** [comment]
@canausa the snapshot functionality already provides what you are asking for. By providing the `-snapshot` argument to `serf agent`, you can have the state stored as it evolves. See the [configuration page](https://serfdom.io/docs/agent/options.html) for details. Thanks!

**Comment by canausa** [comment]
-snapshot is an option but I think the inverse is better which is why I asked for it by default. To me as aa new user this seems like an anti pattern to other linux software. You point is like saying time mysql starts up it is a fresh database unless you tell it to save everything.
