### ISSUE TITLE
Serf query should allow any command

### ISSUE THREAD

**Issue by canausa** [hashicorp/serf#282]
Serf should be allowed to query any arbitrary command that is given to it.

I should not have to define -event-handler "query:load=uptime" instead if the user running serf has access to uptime serf query uptime should just work.

**Comment by ryanuber** [comment]
@canausa Thanks for opening an issue. The goal of `serf query` is not to enable arbitrary remote execution, but to allow asking the set of peers a question and receiving an answer based on each member's configured handlers. This makes the impact of running a query much more predictable, provides the ability to implement a "catch-all" handler, and allows members to ack the message without performing any action for queries which do not concern them.

Using `serf query` as an arbitrary command executor is not an intended use case, and also not something we are planning to add to our roadmap in the short term.

**Comment by canausa** [comment]
Thanks for your take on the mater. I was able to implement this anyways with the following procedure:

serf agent -event-handler "query:bash=/opt/bash.sh"

Bash.sh contains:
#!/bin//bash
bash "$@"

Which allowed to run commands like:
serf query bash "ls /home/canausa"

**Comment by ryanuber** [comment]
@canausa glad to hear that's working for you! Thanks for your response.
