### ISSUE TITLE
Flapping seems to occur between members across subnets. (AWS)

### ISSUE THREAD

**Issue by mhussain** [hashicorp/serf#283]
Hi guys, 

Here is my situation. 

Node A exists in Subnet A and Node B exists in Subnet B. 

Subnet A has ACL's both in and out allowing TCP and UDP on 7946 from Subnet B
Subnet B has ACL's both in and out allowing TCP and UDP on 7946 from Subnet A

What is happening is that when I switch

Node A> serf members 

I see flapping Node B. Which is that I see Node B joins, and then leaves and keeps doing it.

Similarly on Node B.

Node B> serf members

I see a similar thing.

Since both node A and B can see each other, I am thinking that the subnet rules and security group rules are OK in that the serf comms are being allowed to one other. But I am not sure what the flapping means.

Any help would be appreciated.

P.s. I looked through all your closed issues to make sure that I was not flogging a dead horse and all google searches revealed naught.

**Comment by armon** [comment]
I would try the reachability command:
https://serfdom.io/docs/commands/reachability.html

My guess is that there is almost certainly a networking issue at play. In the majority of cases where this is happening, TCP traffic is being allowed while UDP traffic is not. If you use the logs/monitor and notice about a 30 second cadence to the Join/Fail cycle, that is evidence that the TCP-based reconciliation is recovering the failed UDP routing.

**Comment by mhussain** [comment]
Hey @armon 

Thanks for the reply. I just confirmed that both nodes can talk to each other on the port I am using for serf (7946) via both UDP and TCP.

I confirmed TCP by 
$> telnet NODE(A || B)_IP 7946

I got connected to node

and I confirmed UDP by

$> nmap -p 7946 -sU -P0 NODE_(A || B)_IP
PORT     STATE         SERVICE
I get 7946/udp open|filtered unknown

Also the cadence is quicker than 30 seconds. 

:(

**Comment by mhussain** [comment]
OK This is strange. 

The issue was I was not explicitly allowing UDP/7946 outbound on one of the subnets. After allowing that, both nodes are fine. But I still dont understand when I used the before mentioned nmap command to check UDP connectivity for that port across subnets, it said they were both available to be reached 

:( 

Cheers fellows
