### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by slawosz** [hashicorp/serf#284]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with serf. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable serf on @Sourcegraph by going to https://sourcegraph.com/github.com/hashicorp/serf and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by armon** [comment]
Should be enabled!

**Comment by slawosz** [comment]
Cool, thanks!
