### ISSUE TITLE
Enable encryption after agent start

### ISSUE THREAD

**Issue by kaelumania** [hashicorp/serf#292]
I am unable to install or use a new key, when the agent is not started in encryption mode. 
`serf: No keyring to modify (encryption not enabled)`

I think it would be nice if the agent switches automatically to encryption mode when something like `serf keys -install=XXX` is executed.

**Comment by armon** [comment]
@kaelumania Unfortunately this would require a significant rework of internals. A cluster is either fully encrypted or not, so it's an extreme edge case to support a hot switch between the two.

**Comment by ryanuber** [comment]
Agreed with @armon. I also don't think this would be worth it, because we would need to support communication with both unencrypted and encrypted nodes simultaneously, which opens an easy route to defeat the encryption due to the nature of a gossip-based cluster.
