### ISSUE TITLE
Questions regarding state

### ISSUE THREAD

**Issue by asbjornenge** [hashicorp/serf#297]
Hi! I was wondering if there are any documentation regarding how serf treats it's state? What data is stored? Are all events stored forever? If not, for how long? Is it possible to add custom information to the synced state? Etc.

**Comment by armon** [comment]
@asbjornenge There is documentation but it is spread out on the site. Events are stored in a ring buffer, of the last 512 or 1024 events (you'd need to check the defaults, its configurable). They are stored in memory and not persisted. You cannot currently change the synced state to add on.

**Comment by asbjornenge** [comment]
@armon thanks a bunch! Exactly the clarification I was looking for :+1: :smile:
