### ISSUE TITLE
Question: Replace Seed Nodes

### ISSUE THREAD

**Issue by diptanu** [hashicorp/serf#301]
Hi @armon ,

How do you replace a seed node in Serf? I have `RejoinAfterLeave` set to `true` but when a seed node goes down and comes up with the same IP address it can't rejoin the old cluster. All the disks in nodes are ephemeral so we can't use snapshots since when the underlying VM of a seed node is replaced on the cloud the snapshot file would be unavailable.

**Comment by armon** [comment]
@diptanu If its a hard failure, the rest of the cluster should just do the push/pull and it will rejoin he cluster! Nothing you need to do in that case. I'd enable the snapshot file to recover fast from a crash in the agent or any case where you do not lose the state.

**Comment by diptanu** [comment]
@armon I don't see rest of the nodes joining back the cluster when a seed node comes back. I have a feeling, that when a seed node dissapears, the other nodes stops doing push/pull from the seed node when it comes back if the reaper runs and takes the seednode which dissapeared out. 

Example - Node A(seed), Node B and Node C form a cluster. Now the Node A dissapears, and before it came up reapers ran in Node B and Node C so the memberlist in Node B and Node C only shows two nodes. When we start another machine(Node D) with a new distinct name but the same IP as Node A which dissapeared, Node B and Node C will not try to get the new node back in their cluster. Am I missing anything obvious here?

**Comment by relistan** [comment]
I've seen this same behavior if you have only one seed node and it leaves the cluster. If any of the other nodes are also seed nodes and are still in the cluster it no longer has this problem and can rejoin the cluster. You want to have multiple seed nodes and also tell each client about multiple seed nodes. Even in a two node cluster I've found it works best for both to be in the seed list. There is probably a bug there, but the workaround is how most people run it in production anyway, I think.

**Comment by armon** [comment]
Ah yeah is the seed node leaving the cluster? That is an issue then. If the seed node "fails" then the others should try to recover from a partition/failure and you will see the "attempting reconnect" log messages. If the node leaves, then nobody will try to establish contact again.

**Comment by diptanu** [comment]
@armon @relistan Yeah this is when seed nodes leave the cluster. This is a problem on the cloud because imagine on AWS Seed Nodes are on ASG A and apps are in ASG B and ASG C. It's entrirely possible that all nodes in an ASG die or becomes un-available for a few minutes. In that situation it would be awesome if all the other nodes keep trying to re-connect with Seed Nodes and join them back when they become available again. Otherwise when the seed nodes come back, either we have to create a brand new cluster by creating new ASGs for app A and C or do a rolling restart on all the nodes in ASG B and ASG C so that they can join back the cluster.

Is this doable?

**Comment by armon** [comment]
@diptanu Probably the easiest way is to never have the seed nodes leave. Just have them hard fail every time. This way the rest of the cluster will attempt for 72h to establish contact.
