### ISSUE TITLE
Distribute the linux executable as bzip2 or gzip

### ISSUE THREAD

**Issue by Downchuck** [hashicorp/serf#303]
Currently the Linux executables are distributed as zip files; most server-oriented linux distributions do not come with unzip installed, though they do support bzip2, gzip as well as xz (the most compact choice).

**Comment by mitchellh** [comment]
We've been asked this before, but installing zip is pretty easy, and usually not a blocker to using Serf. Using zip currently makes our distribution process a lot easier, although at some point in the future we'll try to use more platform-native formats.
