### ISSUE TITLE
Way to query config data for running agents

### ISSUE THREAD

**Issue by dalehamel** [hashicorp/serf#306]
It would be great if serf responded to a USR signal, or had an RPC call, for dumping the running config of an agent (in JSON).

This would help with debugging, as you could see how multiple JSON files were merged together.

In my case, I want to implement a query that will ask other serf agents to respond with what their event handlers are, so that I know what queries I can issue. I would like to achieve this with another handler script, that would just dump the running config and parse it for the implemented event handlers.

I would be happy to help implement this if it's accepted as a worthwhile feature.

**Comment by slackpad** [comment]
Seems like a good idea. This would probably make the most sense as an RPC call (and maybe output as part of the `info` CLI, or possibly a new one). Consul has a similar capability at /v1/agent/self. We'd definitely want to redact sensitive information like encryption secrets, and only report a safe subset of the configuration.

**Comment by slackpad** [comment]
Going to close this out since there haven't been additional requests for this and you found a simple solution for your use case in #312.
