### ISSUE TITLE
Travis CI build is broken

### ISSUE THREAD

**Issue by slackpad** [hashicorp/serf#307]
It looks like we've picked up a newer version of Go that's enforcing the new internal package limits.

![image](https://cloud.githubusercontent.com/assets/673509/9591349/b4a08216-4fef-11e5-9869-5f12a455e73a.png)

Need to figure out how to fix the build, or clean up Serf to not use the forbidden package.

Here's an example failed build - https://travis-ci.org/hashicorp/serf/builds/78091856.

**Comment by dalehamel** [comment]
:+1: noticed this too, as I don't think either of my PRs should have failed CI.

**Comment by ryanuber** [comment]
There was another issue for this. I think the latest `go.net` will fix this problem. We need to update our fork of that to the latest revision, although we need to be careful to test well as we've had some problems in the past and upstream doesn't guarantee stability.

**Comment by slackpad** [comment]
This looks like it go fixed by https://github.com/hashicorp/go.net/pull/1.
