### ISSUE TITLE
Event handler specially defined for certain roles

### ISSUE THREAD

**Issue by chris-x86-64** [hashicorp/serf#321]
Currently I'm letting bash scripts read the stdin to identify the role of the origin of an event.
I thought it may be good to be able to set event handlers specially defined for members belonging to certain roles. In my opinion, this can save time and eliminate potential bugs caused by users' codes. 

An example snip of a conceptional `/etc/serf.conf`

```
  "event_handlers" : [
    "member-failed:web,member-leave:web=/path/do_this.sh",
    "member-failed:mail,member-leave:mail=/path/do_that.sh"
  ],
```

where `web` and `mail` are role names.

**Comment by slackpad** [comment]
Hi @chris-x86-64 roles are deprecated but this looks like it could work for tags.
