### ISSUE TITLE
Ports used

### ISSUE THREAD

**Issue by thefosk** [hashicorp/serf#329]
I couldn't find a list of ports that Serf uses by default in the docs. Also having a chapter that explains what are the recommended firewall settings in a Serf cluster would be a good addition.

**Comment by slackpad** [comment]
Agreed! I couldn't find a concise place with this information in the docs. Thanks for opening an issue.

**Comment by slackpad** [comment]
Added this in https://github.com/hashicorp/serf/pull/355.
