### ISSUE TITLE
Refuting a suspect message from itself

### ISSUE THREAD

**Issue by slackpad** [hashicorp/serf#336]
In production we noticed that a node logged this during some flapping:

`2015/10/29 20:22:54 [WARN] memberlist: Refuting a suspect message (from: node-10-0-4-146)`

How did the node get a suspect message from itself? The probe code looks like it specifically doesn't probe itself.

We saw another fishy probe:

`2015/10/30 03:21:41 [WARN] memberlist: Refuting a suspect message (from: )`

**Comment by pshima** [comment]
Just logging another record of this:

https://atlas.hashicorp.com/hashicorp/environments/ops/alerts/25526
Critical 'serfhealth' on node node-10-0-4-197
November 2nd 2015, 4:44 pm (2 minutes ago)
`2015/11/03 00:44:47 [WARN] memberlist: Refuting a suspect message (from: node-10-0-4-197)`

**Comment by pshima** [comment]
Logging another instance for record keeping
https://atlas.hashicorp.com/hashicorp/environments/ops/alerts/25534
Critical 'serfhealth' on node node-10-0-5-209
November 3rd 2015, 9:51 am (a few seconds ago)

`2015/11/03 17:51:58 [WARN] memberlist: Refuting a suspect message (from: node-10-0-5-209)`

**Comment by pshima** [comment]
Logging 2 more occurrences
```
10.0.4.125
2015/11/04 00:42:46 [WARN] memberlist: Refuting a suspect message (from: node-10-0-4-125)
10.0.3.28
2015/11/03 23:24:44 [WARN] memberlist: Refuting a suspect message (from: )
2015/11/04 00:42:16 [WARN] memberlist: Refuting a suspect message (from: node-10-0-3-28)
```

**Comment by slackpad** [comment]
Traced this one through and it comes from here:

https://github.com/hashicorp/memberlist/blob/master/state.go#L1008

The node is learning that some other node thinks it's dead or suspect during a push/pull, so the refutation is the right thing to do. Unfortunately, the name of the peer isn't available really at all, so I don't think we can make this better without significant work, which probably isn't worth the effort. I'm going to close this out since it's working properly, and we will see if we can improve the UX as part of the improvements we are making to memberlist.
