### ISSUE TITLE
"force-leave" doesn't trigger "member-leave" event

### ISSUE THREAD

**Issue by thefosk** [hashicorp/serf#345]
I noticed that when a failed node is finally removed from the cluster with `force-leave`, no `member-leave` event is being triggered. Is this intentional?

**Comment by armon** [comment]
I believe this is fixed in master!

**Comment by thefosk** [comment]
Thanks @armon - any plan to release a new version? I see the latest v0.6.4 has been released [around February](https://github.com/hashicorp/serf/compare/v0.6.4...master).

**Comment by slackpad** [comment]
Hi Marco - should be before the end of the year!

**Comment by slackpad** [comment]
Working on the release now. Closing this since the fix is in.
