### ISSUE TITLE
Capture hostname of member leaving the cluster

### ISSUE THREAD

**Issue by ssenaria** [hashicorp/serf#357]
Is there a way to capture the hostname of a node that leaves the cluster? My understanding is that the node that leaves or fails doesn't execute the handler set for "member-leave," so I can't run the handler on said node.

**Comment by slackpad** [comment]
Hi @ssenaria this was fixed in https://github.com/hashicorp/serf/commit/8d364002e80af5c394b1aa53893e8ea3a4a314a7 and should go out with 0.7.0 being released today.
