### ISSUE TITLE
deps/v0-7-0.json missing

### ISSUE THREAD

**Issue by jaapdejong** [hashicorp/serf#360]
Hi,

Please add it to the 0.7.0 release!

Thanks,
Jaap

**Comment by slackpad** [comment]
Hi @jaapdejong are you sure you are pointed at the right tag? That was added and tagged - https://github.com/hashicorp/serf/commit/4bacf8281ef45b93497290328a6ee5f4cec8a170.

**Comment by jaapdejong** [comment]
Hi @slackpad, 
hmmm my bad, sorry for the noise. Not sure what went wrong, but the file is in the repo, that's for sure!
Thanks! Jaap
