### ISSUE TITLE
Why does the serfdom.io redirect/show a www in the domain?

### ISSUE THREAD

**Issue by dragon788** [hashicorp/serf#364]
I can hit most of the other Hashicorp product sites without www in the URL, not sure why if I'm typing https://serfdom.io it works, but if I open it from the main Hashicorp Products page it has the www in front.

**Comment by sethvargo** [comment]
Hi @dragon788 

I just checked, and all of the following domains are working for me:

- https://serfdom.io
- https://www.serfdom.io
- http://serfdom.io (redirects to https)
- http://www.serfdom.io (redirects to https)

Are you experiencing a different behavior?

**Comment by dragon788** [comment]
Hi Seth, this appears to be an OK behavior, I was somewhat concerned due to
the vagrant website not behaving the same way, and I would expect the
redirect to the non-www version just for a consistent appearance, even if
www is valid.

**Comment by sethvargo** [comment]
Hi @dragon788 

As we update our websites, we will be forcing everything to https://www, but it's a slow process.

**Comment by dragon788** [comment]
I would guess this is so the website shows up separately from the
documentation pages which may be hosted at https://docs.whatever.com?
Either way keep up the good work.
