### ISSUE TITLE
RPC response length

### ISSUE THREAD

**Issue by thefosk** [hashicorp/serf#368]
I have a question about the RPC protocol. I am building a Lua client for Serf, and I am having an hard time understanding how to properly parse a response.

A response can be made by a header and optionally a body, each one of them is encoded with MessagePack. But how do I know when a response ends? Is there any termination character at the end, or is there any indication on the response length so that I know how many bytes to read?

**Comment by slackpad** [comment]
Hi @thefosk were you able to figure this out? I believe that msgpack does the length encoding as part of its protocol, so you should be able to feed bytes into your decoder and let it figure out what the endcoded structures are.

**Comment by thefosk** [comment]
Yep, I got it. Thanks.
