### ISSUE TITLE
Convergence Simulator is broken on the website

### ISSUE THREAD

**Issue by eliquious** [hashicorp/serf#374]
Just a heads up. The simulator is broken on the Serf website.

**Comment by slackpad** [comment]
Hi @eliquious thanks for the report - we will take a look.

**Comment by slackpad** [comment]
We fixed the live site and @sethvargo will take a look at the root cause so future deployments don't revert the fix.

**Comment by slackpad** [comment]
Scripting is in place now to fix up the mime types.
