### ISSUE TITLE
can't configure GossipInterval and GossipNodes

### ISSUE THREAD

**Issue by linshaoyong** [hashicorp/serf#397]
[https://www.serfdom.io/docs/internals/simulator.html](url)
I read the document above, I think GossipInterval and GossipNodes are important.
But I can't configure memberlist.

my program generates many logs like this:
2016/07/07 13:11:28 [WARN] serf: received old event test from time 760436 (current: 762201)
2016/07/07 13:11:28 [WARN] serf: received old event test from time 753874 (current: 762201)
2016/07/07 13:11:28 [WARN] serf: received old event test from time 756286 (current: 762201)

GossipInterval's default value is 0.2 seconds, is less value help?

**Comment by dimbleby** [comment]
duplicates #252, and would be addressed by #341 - if that were revived
