### ISSUE TITLE
deps for 0.8.0 missing

### ISSUE THREAD

**Issue by jaapdejong** [hashicorp/serf#410]
The dependencies file for version 0.8.0 is missing.

**Comment by slackpad** [comment]
Hi @jaapdejong we switched to govendor so now it's not a separate thing we create, but it's managed with the rest of the code. You can get the 0.8 version here:

https://github.com/hashicorp/serf/blob/v0.8.0/vendor/vendor.json

**Comment by jaapdejong** [comment]
ah oke thanks!
