### ISSUE TITLE
Issues when building serf

### ISSUE THREAD

**Issue by jaapdejong** [hashicorp/serf#411]
Hi,

I ran into a few (minor) issues while building serf:
- go compiler >= 1.6 (it will not translate otherwise)
- error message when amd64 (hostarch) not specified in XC_ARCH
- must unset GOOS and GOARCH (gox and govendor compiled for wrong arch...)
- testrun fails

Jaap

**Comment by jen20** [comment]
Hi @jaapdejong! Thanks for opening this issue, and sorry for the rather extreme delay in replying. I'm not sure that much is actionable here - building seems to work ok for me with the latest Go toolchain, although it's no longer important to use `gox`. If this is still causing you problems, feel free to comment here and I'll reopen and investigate further.
