### ISSUE TITLE
How do I send a message directly to another node?

### ISSUE THREAD

**Issue by F21** [hashicorp/serf#423]
`hashicorp/memberlist` has a `SendToTCP()` to directly send to another node. However, serf does not have an equivalent method. Serf also uses custom its own delegates, so it does not appear to be possible to implement my own delegate to receive a message sent over `SendToTCP()`.

How do I use serf to send a message directly to another node over TCP?

**Comment by henderbj** [comment]
If you want to send a short message to a serf member you can use user events or queries. You can even restrict with tags and then all members with that tag will receive your message. Please check documentation about:
Event Handlers: https://www.serf.io/docs/agent/event-handlers.html
Custom Events: https://www.serf.io/docs/commands/event.html

I hope it helps.

**Comment by F21** [comment]
@henderbj Thanks! In my case I plan to use serf as a go library for a distributed application. According to the docs, there doesn't appear to be a way to send an event to specific nodes using their IP address, so queries might be the best way to go here. However, I hope `SendToTCP()` could be surfaced to the serf API in the future as it would be useful for simple use-cases where we just want to send messages directly to 1 node, without having to do a broadcast and filter on that.

**Comment by slackpad** [comment]
Hi @F21 that's probably best done by getting the address of the member from Serf and connecting up in your application. That's what we do in apps like Consul that build upon Serf, and up at that level we figure out which port to use (based on Serf tags we set), set up TLS, etc.
