### ISSUE TITLE
join to all other members if possible

### ISSUE THREAD

**Issue by vtolstov** [hashicorp/serf#431]
I have 5 data centers each run serf.
I want to connect this dc  to each other. So i want to add in agent config file addresses of other serf on other dc and join to it if possible.
But i don't want to fail to start agent if one dc is down or first serf agent is down on one dc.
How can i deal with this ?
Also on each dc serf running on local interface, that does not wan access, but each dc can connect only wan. So on each node in dc that acts like relay or proxy i need to run two serf agents? One on local network and second on wan interface? And they join to each other?

**Comment by slackpad** [comment]
Hi @vtolstov https://www.serf.io/docs/agent/options.html#_retry_join can be used to try to join with other servers at startup but continue on if the join fails.

We don't have a proxy like that in Serf. You might want to check out Consul https://www.consul.io/docs/guides/datacenters.html which has a closer fit for that use case. Consul servers have two Serf instances internally, one LAN and one WAN. Consul lets you route requests to Consul to servers in other datacenters via WAN. Hope that helps!
