### ISSUE TITLE
Possible data race in accessing serf.eventJoinIgnore

### ISSUE THREAD

**Issue by ilog** [hashicorp/serf#435]
serf/delegate.go:233 is accessing the serf.eventJoinIgnore without acquiring the joinLock

WARNING: DATA RACE

Read at 0x00c4201822a0 by goroutine 39:
  github.com/hashicorp/serf/serf.(*delegate).MergeRemoteState()
      /go/src/github.com/hashicorp/serf/serf/delegate.go:233 +0x8e3
  github.com/hashicorp/memberlist.(*Memberlist).mergeRemoteState()
     /go/src/github.com/hashicorp/serf/vendor/github.com/hashicorp/memberlist/net.go:958 +0x803
  github.com/hashicorp/serf/vendor/github.com/hashicorp/memberlist.(*Memberlist).handleConn()
      /go/src/github.com/hashicorp/serf/vendor/github.com/hashicorp/memberlist/net.go:231 +0xc39

Previous write at 0x00c4201822a0 by goroutine 22:
  github.com/hashicorp/serf/serf.(*Serf).Join.func1()
      /go/src/github.com/hashicorp/serf/serf/serf.go:634 +0x3f
  github.com/hashicorp/serf/serf.(*Serf).Join()
      /go/src/github.com/hashicorp/serf/serf/serf.go:649 +0x145

**Comment by deckarep** [comment]
https://github.com/hashicorp/serf/pull/464 is my attempt to fix this data-race.  

1. Although the Serf object properly locks the mutex internally: https://github.com/hashicorp/serf/blob/master/serf/serf.go#L595 for the scope of the function.
2. The `MergeRemoteState` method has an unsynchronized access to the `serf.eventJoinIgnore` field here: https://github.com/hashicorp/serf/blob/master/serf/delegate.go#L254

**Comment by jen20** [comment]
This was addressed by 4f3b7b4 as per the comments on #464, so I'm going to close this issue out. Please feel free to re-open if there is further information here!
