### ISSUE TITLE
non-deterministic time execution of event handlers

### ISSUE THREAD

**Issue by scanterog** [hashicorp/serf#436]
Hi guys,

We're having 'random' time execution after some node receive an event, in this case 'member-failed' event. Example:

> Jan  6 12:39:04 b02-sandbox serf[1707]:     2017/01/06 12:39:04 [INFO] serf: EventMemberFailed: b01-sandbox 10.100.0.1
> Jan  6 12:39:05 b02-sandbox serf[1707]:     2017/01/06 12:39:05 [INFO] agent: Received event: member-failed
> Jan  6 12:39:06 b02-sandbox serf[1707]:     2017/01/06 12:39:06 [WARN] agent: Script /etc/serf/main_handler.sh' slow, execution exceeding 1s
> ....
> Jan  6 12:39:21 b02-sandbox serf[1707]:     2017/01/06 12:39:09 [DEBUG] agent: Event 'member-failed' script output: [serf:debug => inside main_handler script]

In this example, it took around 15 seconds between the 'slow execution message' and the script output. But it can take sometimes 1 second, 12 seconds, or even close to a minute. What is the expected behavior?

**Comment by slackpad** [comment]
Hi @scanterog that looks like the script itself is slow to respond. Is there something it's blocking on or something like that?

**Comment by scanterog** [comment]
Hi @slackpad ! Yes, finally we've found that it was an issue with the event handler script. We've tested it and serf is working as expected. Thanks!
