### ISSUE TITLE
Can't download from TravisCI

### ISSUE THREAD

**Issue by thefosk** [hashicorp/serf#437]
Since a few days TravisCI complains that the SSL certificate used when downloading Serf is not valid. Can you take a look into it?

```
$ wget https://releases.hashicorp.com/serf/0.8.0/serf_0.8.0_linux_amd64.zip
--2017-01-18 21:25:45--  https://releases.hashicorp.com/serf/0.8.0/serf_0.8.0_linux_amd64.zip
Resolving releases.hashicorp.com (releases.hashicorp.com)... 151.101.33.183
Connecting to releases.hashicorp.com (releases.hashicorp.com)|151.101.33.183|:443... connected.
Unable to establish SSL connection.
```

**Comment by slackpad** [comment]
Hi @thefosk we recently switched our releases service to require TLS 1.2. If you enable https://docs.travis-ci.com/user/trusty-ci-environment/ for your builds it should be able to work with the new requirements.

**Comment by thefosk** [comment]
thanks, that worked.
