### ISSUE TITLE
ShutdownCh not useful

### ISSUE THREAD

**Issue by nathanielc** [hashicorp/serf#453]
I am consuming serf as a library and my application can be instructed to join and leave different serf clusters during the lifetime of the application. I am running into an race condition where a leave is followed quickly by a Create for a new serf instance, causing an error binding to the interface since the listener hasn't been closed yet. I am using the ShutdownCh to wait till the serf instance is completely shutdown before calling Create on a new instance. 

I took a look at the code here https://github.com/hashicorp/serf/blob/master/serf/serf.go#L811 and the shutdown channel is closed before the memberlist object is closed. This leaves a small window for a race condition where memberlist hasn't released the bound interface before the next call to Create tries to bind to it.

Is this a bug or is there a reason that the shutdownCh has to be closed before the memberlist object is closed?

**Comment by slackpad** [comment]
Hi @nathanielc I think we can move the close after. I've also got a PR in work for memberlist that will make memberlist wait for all the listeners to see the close before the shutdown completes - https://github.com/hashicorp/memberlist/blob/transport/net_transport.go#L215-L216.
