### ISSUE TITLE
serf on smartos/solaris not binding to all interfaces. failing to start.

### ISSUE THREAD

**Issue by Multikas** [hashicorp/serf#466]
[server ~]# ifconfig -a
lo0: flags=2001000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv4,VIRTUAL> mtu 8232 index 1
        inet 127.0.0.1 netmask ff000000
net0: flags=201000843<UP,BROADCAST,RUNNING,MULTICAST,IPv4,CoS> mtu 1500 index 2
        inet 10.10.10.1 netmask ffffff00 broadcast 195.12.188.255
        ether 82:ee:e:2f:7a:f0
lo0: flags=2002000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv6,VIRTUAL> mtu 8252 index 1
        inet6 ::1/128
net0: flags=202004841<UP,RUNNING,MULTICAST,DHCP,IPv6,CoS> mtu 1500 index 2
        inet6 fe80::80ee:eff:fe2f:7af0/10
        ether 82:ee:e:2f:7a:f0
net0:1: flags=202000841<UP,RUNNING,MULTICAST,IPv6,CoS> mtu 1500 index 2
        inet6 2001:DB8::dead/64

[server ~]# /opt/serf/serf agent
==> Starting Serf agent...
==> Failed to start the Serf agent: Error creating Serf: Failed to create memberlist: No private IP address found, and explicit IP not provided

if I starting it with -bind flag - it works, but listens only on that particular IP.

**Comment by jen20** [comment]
Hi @Multikas, sorry for the delay in replying here. I'll test this with a later verison of Serf, but I believe there was a problem with the output of `net.Interfaces` on Solaris-derived systems at some point in the past which may now have been rectified.

**Comment by jen20** [comment]
I've traced this down so far to being a problem with `memberlist` rather than Serf proper. I'll continue to track it down there...

**Comment by jen20** [comment]
Hi @Multikas, this is a fairly straightforward fix, verified on a SmartOS zone using base-64 v18.1.0 (image 221635c4).
