### ISSUE TITLE
Question : Embedding serf agent in a go application

### ISSUE THREAD

**Issue by pkrishn6** [hashicorp/serf#484]
Hello,
I am trying to containerize my multi-daemon (written in Go) application with one daemon in a container. I am planning to have one serf agent per container(daemon) and achieve service discovery this way.

All examples point to agent running as separate proces. I am looking for pointers on how to embed serf agent in my daemon and make API calls instead of making RPC calls using serf client.

Thanks.

**Comment by slackpad** [comment]
Hi @pkrishn6 that's a pretty common way to use Serf - you can take a look at Consul for an example - https://github.com/hashicorp/consul/blob/v0.9.3/agent/consul/server_serf.go. Hope that helps!

**Comment by pkrishn6** [comment]
@slackpad: thanks much for your reply and pointer.
