### ISSUE TITLE
member status is not updated while the machine is not reachable (i/o timeout)

### ISSUE THREAD

**Issue by lisa006** [hashicorp/serf#498]
![serf-timeout-test](https://user-images.githubusercontent.com/35121761/34592083-7896cc1e-f176-11e7-87f8-96ee3bf5bb4e.GIF)

Please find the attached screenshot.

I started Serf Agent ("serf.exe agent") in two machines and join them into the cluster. Then, I set up the firewall in machine A to block the port (7946) used by Serf Agent. From the output message, both Serf Agents started showing  error -
machine A threw the error: "2018/01/05 01:43:32 [ERR] memberlist: Push/Pull with std000001 failed: dial tcp 10.0.0.5:7946: i/o timeout"

machine B threw the error: "2018/01/05 01:45:23 [ERR] memberlist: Push/Pull with std000000 failed: dial tcp 10.0.0.4:7946: i/o timeout"

However, waiting for a few hours, run "serf members" command, both machines shows "alive" status. Is that expected?

**Comment by slackpad** [comment]
Hi @lisa006 it looks like you blocked TCP but not UDP for that port, so they were still able to probe each other, just not perform periodic anti-entropy syncs. If you block both protocols they should see each other as failed. Hope that helps!
