### ISSUE TITLE
_highcharts.js is copyrighted material

### ISSUE THREAD

**Issue by gcapizzi** [hashicorp/serf#564]
[`website/source/assets/javascripts/lib/_highcharts.js`](https://github.com/hashicorp/serf/blob/master/website/source/assets/javascripts/lib/_highcharts.js) is copyright of Highsoft and its [license](https://shop.highsoft.com/media/highsoft/Standard-License-Agreement-11.0.pdf) is definitely not open source, so it should probably be removed.

**Comment by luisapace** [comment]
Hi, may I kindly ask if there is any update on this? Thanks

**Comment by johncowen** [comment]
Hi @luisapace and @gcapizzi 

We're looking into this, thanks for raising this issue.

Thanks,

John

**Comment by johncowen** [comment]
Hi @luisapace and @gcapizzi,

Thanks again for raising this issue, we've purchased a licence for this from Highsoft and they've approved it to be in our repository. If you have any further questions please let us now.

Thankyou!

John

**Comment by luisapace** [comment]
Hi, you have purchased a licence for this from Highsoft and they've approved it to be in our repository, but what about reuse it in other code after having downloaded your code? Could be possible to include here that license text? thanks.

**Comment by johncowen** [comment]
Hi @luisapace,

Highsoft approved this code to be in our repository as is, also I’m not sure if it helps but the source code contains a link to the license at the top. This code is only used for our documentation website, not serf itself. Let me know if that helps.

Thanks,
