### ISSUE TITLE
Serf build failure at 0.8.4 

### ISSUE THREAD

**Issue by akshaykumarvijapur** [hashicorp/serf#591]

**Comment by akshaykumarvijapur** [comment]
Please fix the build.

**Comment by rboyer** [comment]
Can you clarify under what circumstances you experienced a build failure? After I check out the `v0.8.4` tag and run `make bin` that all works fine. Also a straight `go install ./cmd/serf` also does not appear to fail.

```
$ go version
go version go1.12.13 linux/amd64
```

**Comment by akshaykumarvijapur** [comment]
Seems like it is working now. Thanks
