### ISSUE TITLE
Build Failing 

### ISSUE THREAD

**Issue by akshayvijapur** [hashicorp/serf#597]
Hi Team ,

We are encountering this error.

go get github.com/hashicorp/serf/client

undefined: memberlist.Address
/data/src/github.com/hashicorp/serf/serf/delegate.go:111:30: d.serf.memberlist.SendToAddress undefined (type *memberlist.Memberlist has no field or method SendToAddress)
/data/src/github.com/hashicorp/serf/serf/event.go:169:10: undefined: memberlist.Address
/data/src/github.com/hashicorp/serf/serf/event.go:173:29: q.serf.memberlist.SendToAddress undefined (type *memberlist.Memberlist has no field or method SendToAddress)
/data/src/github.com/hashicorp/serf/serf/query.go:282:16: undefined: memberlist.Address
/data/src/github.com/hashicorp/serf/serf/query.go:286:25: s.memberlist.SendToAddress undefined (type *memberlist.Memberlist has no field or method SendToAddress)
/data/src/github.com/hashicorp/serf/serf/serf.go:1331:12: undefined: memberlist.Address
/data/src/github.com/hashicorp/serf/serf/serf.go:1335:26: s.memberlist.SendToAddress undefined (type *memberlist.Memberlist has no field or method SendToAddress)

Please check,

Thanks,
Akshay

**Comment by akshayvijapur** [comment]
https://github.com/hashicorp/serf/tree/v0.8.4 we are 0.8.4

**Comment by mkeeler** [comment]
What version of Go are you using? Are you compiling with modules enabled. I just executed `GO111MODULE=on go get github.com/hashicorp/serf/client@v0.8.4`  and it compiled correctly for me.

**Comment by akshayvijapur** [comment]
Can you please try  go get github.com/hashicorp/serf/client

**Comment by mkeeler** [comment]
I can reproduce it in GOPATH mode. Apparently we missed updating our vendor dir which is why things work in module mode but not GOPATH (since the vendor dir is ignored for module mode)

One other thing to mention is that when you are pulling the code in this manner you are not getting v0.8.4 but rather whatever is in master. From the looks of it that is not your desire.

**Comment by akshayvijapur** [comment]
We were using serf 0.8.4. But for compiling we are using master. Anyway thanks for quick fixes.
