### ISSUE TITLE
Serf client cannot connect to RPC client running locally (question)

### ISSUE THREAD

**Issue by gerep** [hashicorp/serf#603]
I am initializing my agent like this:
```
    conf := serf.DefaultConfig()
    conf.NodeName = "node-a"
    conf.MemberlistConfig.BindAddr = "127.0.0.1"
    conf.MemberlistConfig.BindPort = 6666
    conf.MemberlistConfig.AdvertiseAddr = "127.0.0.1"
    conf.MemberlistConfig.AdvertisePort = 6666
```
I also have a client code that is trying to connect to the RPC client:
```
    c, err := client.NewRPCClient("127.0.0.1:7373")
    if err != nil {
        fmt.Println("error creating RCP Client:", err)
        return
    }
```
I start my agent and I see this output:
```
2020/05/06 07:15:18 [INFO] serf: EventMemberJoin: node-a 127.0.0.1
[{node-a 127.0.0.1 6666 map[] alive 1 5 2 2 5 4}]
```

When I start my client, I get this:

```
error creating RCP Client: dial tcp 127.0.0.1:7373: connect: connection refused
```

If I start the agent using the CLI as in: `serf agent -bind=0.0.0.0:6667 -advertise=0.0.0.0:6667 -join=0.0.0.0:6666 -node=agent-2 -log-level=debug` and run my client code, it connects to the RPC client.

I am sure there is a mistake in my code or in my understanding of how Serf works.

**Comment by max19931** [comment]
if you not know serf, read the official docs on it!!!!!

can be found here: https://www.serf.io/docs/index.html

**Comment by gerep** [comment]
I have read it @max19931 and I don't know where in the docs I can find the solution for this problem. Can you help?

**Comment by donmstewart** [comment]
@gerep Did you fix it as I have the same issue and I too have read the docs. I have tried `ClientFromConfig(&client.Config)` as well to no avail.

**Comment by gerep** [comment]
Hi @donmstewart, the problem was in my understanding of the tool. I was trying to make my serf agents connect to each other but it turns out it is not required, they will find themselves base in your `Join()` call.
