### ISSUE TITLE
How to use serf as a developer?

### ISSUE THREAD

**Issue by vision9527** [hashicorp/serf#610]
hello, is there more code demo about serf's use in go?

**Comment by s-christoff** [comment]
Howdy @vision9527 ,

I think the best example on how to use Serf can be seen in [Consul](https://www.consul.io/intro/vs/serf).  There is also this talk about how [Fastly uses Serf](https://www.hashicorp.com/resources/health-checking-service-serf/), which I find super informational! Lastly, we do have a [demos folder here](https://github.com/hashicorp/serf/tree/master/demo). 

I hope this answers your question!
